### ISSUE TITLE
IPC launch of application crashes oxide

### ISSUE THREAD

**Issue by FelixSchladt** [DHBW-FN/OxideWM#215]
## Found in
    
- 1bb081de0084f2f3a5f7521ff291ad8414b8275a
- Current main https://github.com/DHBW-FN/OxideWM/commits/main

## Description

When opening a program with
```bash
oxide-msg -c exec -a kitty
```
the programm does not open and the statusbar workspace bar gets weird.
If the command is executed again the following error is displayed:

```sh
2023-02-23 17:19:33 - [INFO]: Handle wm command Command: QuitWorkspace, Args: kitty
2023-02-23 17:19:33 - [INFO]: quitting workspace 1
2023-02-23 17:19:33 - [INFO]: quitting workspace 1
2023-02-23 17:19:33 - [INFO]: quit workspace 1, switching to 1
2023-02-23 17:19:33 - [INFO]: quitting workspace 1
2023-02-23 17:19:33 - [WARN]: could not quit workspace QuitError: failed to set new workspace, after no workspace was present
2023-02-23 17:19:33 - [INFO]: state change signal
2023-02-23 17:19:38 - [INFO]: Handle wm command Command: QuitWorkspace, Args: kitty
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/windowmanager/mod.rs:123:44
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
   3: core::option::Option<T>::unwrap
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/option.rs:778:21
   4: oxide::windowmanager::WindowManager::get_active_workspace
             at ./src/windowmanager/mod.rs:123:9
   5: oxide::windowmanager::WindowManager::handle_quit_workspace
             at ./src/windowmanager/mod.rs:243:37
   6: oxide::eventhandler::EventHandler::handle_wm_command
             at ./src/eventhandler/mod.rs:171:42
   7: oxide::eventhandler::EventHandler::handle_ipc_event
             at ./src/eventhandler/mod.rs:135:13
   8: oxide::eventhandler::EventHandler::run_event_loop
             at ./src/eventhandler/mod.rs:49:25
   9: oxide::main
             at ./src/main.rs:102:9
  10: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
xinit: connection to X server lost
```

## Comments
this seems to be related to the current workspace somehow. 
This is strange as this worked a few commits up the road and therefore is probably connected to a recent change.

**Comment by janschaible** [comment]
can you reproduce the error ?:) works just fine on my laptop... :/

**Comment by FelixSchladt** [comment]
after reproduction failed in newer version it seems this bug is fixed
